name: Deploy Parrot Flint Uptime Robot

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
      - 'main'

jobs:
  deploy-crawler:
    name: Deploy Parrot Flint Uptime Robot to Fly.io
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: >
          flyctl deploy ./
          --ha=false
          --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
